In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix

# display results to 3 decimal points, not in scientific notation
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
user_data = pd.read_table('/cxldata/gle/usersha1-artmbid-artname-plays.tsv',
                          header = None, nrows = 2e7,
                          names = ['users', 'musicbrainz-artist-id', 'artist-name', 'plays'],
                          usecols = ['users', 'artist-name', 'plays'])
user_profiles = pd.read_table('/cxldata/gle/usersha1-profile.tsv',
                          header = None,
                          names = ['users', 'gender', 'age', 'country', 'signup'],
                          usecols = ['users', 'country'])

In [3]:
user_data.head()

users           artist-name  plays
0  00000c289a1829a808ac09c00daf10bc3c4e223b       betty blowtorch   2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b             die Ärzte   1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b     melissa etheridge    897
3  00000c289a1829a808ac09c00daf10bc3c4e223b             elvenking    717
4  00000c289a1829a808ac09c00daf10bc3c4e223b  juliette & the licks    706

In [4]:
user_profiles.head()

users        country
0  00000c289a1829a808ac09c00daf10bc3c4e223b        Germany
1  00001411dc427966b17297bf4d69e7e193135d89         Canada
2  00004d2ac9316e22dc007ab2243d6fcb239e707d        Germany
3  000063d3fe1cf2ba248b9e3c3f0334845a27a6bf         Mexico
4  00007a47085b9aab8af55f52ec8846ac479ac4fe  United States

In [5]:
user_data[user_data['artist-name'].isnull()]

users artist-name  plays
244853    039e5d61d65bbf5e6d95b07b1b3b67f7fd287a62         NaN     18
431015    065a001be5a8a55971042077933e263d0d5cde46         NaN    186
455721    06b17c50402d06a497cb13a0375992fd1e90b392         NaN      3
504026    0757ac29973aab69bb31cd164c6df975bf4df9a1         NaN     38
607282    08e102b376abe856a3d4be5ea14ad6b37395fe82         NaN    208
638945    09587336c1c5ab850fa8216faea53cc4a03a2e0d         NaN      2
686081    0a05c798f9979b0bb815f74284a17e8f1c6c2cb4         NaN     36
1117649   103e539147a6952fd1769498138fab82dff47a35         NaN     35
1155078   10d6b8b61f976e20334f279e3c6b79594b7e14d8         NaN      9
1191415   11611e90a0ec78aee3f65dcc4b5bc586aa4c7124         NaN     17
1220637   11cf3420b28ca39e1e4aa2096ad798dc7474ba4e         NaN     19
1335807   1376ce8a6457cc0869062cb5fa507bb5da06d485         NaN      4
1372997   1401fac14e682ed1fb7e1f4143a93b55050902cd         NaN      3
1388492   143b78ba7c2d9f8fa8a80b798a0e7516434123f7         NaN     31
1488765   15ad19502deb87129034577f8c7bfc4127c49b87         NaN     48
1503814   15ebae9028b6c6cda320611e290e2752971dfe31         NaN      7
1511812   160c367ddf18f1848912a045d7152e1f33c4c0a5         NaN     16
1589995   173417c7e2cae36c9dfc8ab6e91f1f85bd3126b6         NaN     93
1638398   17e2fe3f982a8a51e049936b7eaddb384a636b14         NaN    146
1753239   1998d5324b882cbb77eec1e139cec060649d8b57         NaN     95
1833472   1acdd851af4b44e5391706752b9e1ce3be525890         NaN     40
1949872   1c77e604bcef683f2336b8cca2a2b6986e64fac3         NaN     23
1956888   1c95199677e08d908db64939b0496b4b175396d1         NaN     20
2052860   1df268a1c7796911d64658ded8df428f6877ef30         NaN     22
2085271   1e60094abce558ac5b1acd7db81b7f2019888713         NaN     38
2106381   1eb1999e6b3bd98824833419868b2e6df3dbfdd2         NaN      6
2119850   1ee0b552987d0bd1c6a1d5ac4d87fb9cbd0194f4         NaN     14
2260456   20eabb43c733f328defc8c55a563d4163cb56403         NaN      6
2421389   2362424dfc48e31dbfacd3751b0b7cad3f806249         NaN    103
2435019   23976825a19214cdc16e164abbd5240a36df0440         NaN   1391
...                                            ...         ...    ...
14476247  d35feea3013a775436e2f3d4a738f5d76250a477         NaN     67
14525925  d4104181584f61f42f8de0f05a337bbdf1eef76e         NaN     46
14800624  d8104feebb917e95640cd7d0787a2ae9a72a8b71         NaN      6
14801833  d81573cb03a48e8839396156d8bfbac8017d2322         NaN    104
14959895  da5e37df94e0219a66d6d4b2455b561e702cbc83         NaN     40
15065613  dbef6b6d8a6e357624716238f971c73ef25418c9         NaN     23
15220231  de35df7bcb4ac8e4990991596010ab2ccbc2c655         NaN    259
15278800  df14892102dc784dd95e35e2aeb29196e24adfe1         NaN     22
15362578  e043b313cfa1e9e31ff6438b5782d93c472c908d         NaN     26
15413469  e102c7b0dc902ea2d9c13332ac9078a0dc6d7c62         NaN    140
15436212  e1582df53473b2c7cad44e98c70f15e03adf5d4a         NaN    131
15675704  e4f33fcac6115b183d6caaa1bcffaeb8f9793cf7         NaN     12
15753822  e62ebd7563fed4d25856db7788ac851c0bfa21d5         NaN     40
15790455  e6b946190dedfc86f5c8c0685c89afa09dede3f7         NaN     27
15891098  e8314d67ad10fc5d8e1c6916b7d571e6df258744         NaN     28
15964976  e9459f2de308a16494a7b2694ccf0e8309c4ac13         NaN     16
16107065  eb49dd9dc4a9ae493f50c5ccf08146e1e27da391         NaN    640
16242768  ed3e4e35f70fa95d64a5c5afd33321a0c1aca22d         NaN      1
16279903  edc98f869ba4f9d42c0745adf467cd8d9cb199da         NaN    253
16569212  f1e50dbd40f89af0a00cd283d6b611825110eaf6         NaN    719
16675082  f3645620bdc3a072ce56e81e2f6b3bcbb6148271         NaN      4
17047888  f8cc72d5126306243bb4732c0540bdae3b6266bb         NaN     40
17127251  fa000b8cf4a554e1ee9351cef8b7413bf91d32d3         NaN      6
17142202  fa3bdd13819f518fdbc9317d087b551c0b63333b         NaN      4
17219864  fb6185eb353980dd59ccf102d67115d59429d36a         NaN     17
17227026  fb7aec57827b2bd6152b84ef2034bc5aa023fe89     

In [6]:
if user_data['artist-name'].isnull().sum() > 0:
    user_data = user_data.dropna(axis = 0, subset = ['artist-name'])

In [7]:
user_data[user_data['artist-name'].isnull()]

Empty DataFrame
Columns: [users, artist-name, plays]
Index: []

In [9]:
artist_plays = (user_data.
     groupby(by = ['artist-name'])['plays'].
     sum().
     reset_index().
    rename(columns = {'plays': 'total_artist_plays'})
     [['artist-name', 'total_artist_plays']])
artist_plays.head()

artist-name  total_artist_plays
0                                       04)]                   6
1                                         2                 1606
2                                  58725ab=>                  23
3   80lİ yillarin tÜrkÇe sÖzlÜ aŞk Şarkilari                  70
4                              amy winehouse                  23

In [10]:
user_data_with_artist_plays = user_data.merge(artist_plays, left_on = 'artist-name', right_on = 'artist-name', how = 'left')
user_data_with_artist_plays.head()

users           artist-name  plays  \
0  00000c289a1829a808ac09c00daf10bc3c4e223b       betty blowtorch   2137   
1  00000c289a1829a808ac09c00daf10bc3c4e223b             die Ärzte   1099   
2  00000c289a1829a808ac09c00daf10bc3c4e223b     melissa etheridge    897   
3  00000c289a1829a808ac09c00daf10bc3c4e223b             elvenking    717   
4  00000c289a1829a808ac09c00daf10bc3c4e223b  juliette & the licks    706   

   total_artist_plays  
0               25651  
1             3704875  
2              180391  
3              410725  
4               90498

In [11]:
artist_plays['total_artist_plays'].describe()

count     292363.000
mean       12907.022
std       185981.631
min            1.000
25%           53.000
50%          208.000
75%         1048.000
max     30466827.000
Name: total_artist_plays, dtype: float64

In [11]:
artist_plays['total_artist_plays'].max()

30466827

In [12]:
artist_plays[artist_plays['total_artist_plays']==artist_plays['total_artist_plays'].max()]

artist-name  total_artist_plays
252494  the beatles            30466827

In [12]:
artist_plays[artist_plays['total_artist_plays']==artist_plays['total_artist_plays'].max()]

artist-name  total_artist_plays
252494  the beatles            30466827

In [13]:
artist_plays['total_artist_plays'].quantile(np.arange(.9, 1, .01)), 

(0.900     6137.800
 0.910     7409.420
 0.920     9102.040
 0.930    11474.660
 0.940    14898.000
 0.950    19964.500
 0.960    28420.120
 0.970    43541.420
 0.980    79403.560
 0.990   198483.660
 Name: total_artist_plays, dtype: float64,)

In [14]:
artist_plays['total_artist_plays'].value_counts()

1          2816
2          2724
3          2365
4          2211
5          2123
6          2036
7          1907
8          1874
9          1833
12         1825
10         1786
11         1663
16         1640
14         1638
13         1621
15         1591
20         1476
19         1474
18         1467
17         1448
22         1355
23         1330
24         1320
21         1305
25         1289
26         1265
28         1249
30         1243
29         1223
27         1205
           ... 
87972         1
73645         1
143307        1
296990        1
22660         1
18566         1
16519         1
8331          1
213149        1
458577        1
327441        1
646837        1
134607        1
443734        1
123081        1
40349         1
75178         1
1641903       1
144840        1
2244041       1
22148         1
655025        1
16009         1
7821          1
63120         1
52887         1
40605         1
36511         1
67246         1
21621         1
Name: total_artist_plays

# Taking only top artist (where no of plays are more)


In [22]:
popularity_threshold = 40000
user_data_popular_artists = user_data_with_artist_plays.query('total_artist_plays >= @popularity_threshold')
user_data_popular_artists.head()

users            artist-name  plays  \
1  00000c289a1829a808ac09c00daf10bc3c4e223b              die Ärzte   1099   
2  00000c289a1829a808ac09c00daf10bc3c4e223b      melissa etheridge    897   
3  00000c289a1829a808ac09c00daf10bc3c4e223b              elvenking    717   
4  00000c289a1829a808ac09c00daf10bc3c4e223b   juliette & the licks    706   
5  00000c289a1829a808ac09c00daf10bc3c4e223b  red hot chili peppers    691   

   total_artist_plays  
1             3704875  
2              180391  
3              410725  
4               90498  
5            13547741

In [15]:
user_data_with_artist_plays.head()

users           artist-name  plays  \
0  00000c289a1829a808ac09c00daf10bc3c4e223b       betty blowtorch   2137   
1  00000c289a1829a808ac09c00daf10bc3c4e223b             die Ärzte   1099   
2  00000c289a1829a808ac09c00daf10bc3c4e223b     melissa etheridge    897   
3  00000c289a1829a808ac09c00daf10bc3c4e223b             elvenking    717   
4  00000c289a1829a808ac09c00daf10bc3c4e223b  juliette & the licks    706   

   total_artist_plays  
0               25651  
1             3704875  
2              180391  
3              410725  
4               90498

In [23]:
user_data_popular_artists.head(100)

users                artist-name  \
1    00000c289a1829a808ac09c00daf10bc3c4e223b                  die Ärzte   
2    00000c289a1829a808ac09c00daf10bc3c4e223b          melissa etheridge   
3    00000c289a1829a808ac09c00daf10bc3c4e223b                  elvenking   
4    00000c289a1829a808ac09c00daf10bc3c4e223b       juliette & the licks   
5    00000c289a1829a808ac09c00daf10bc3c4e223b      red hot chili peppers   
6    00000c289a1829a808ac09c00daf10bc3c4e223b                     magica   
7    00000c289a1829a808ac09c00daf10bc3c4e223b    the black dahlia murder   
8    00000c289a1829a808ac09c00daf10bc3c4e223b                the murmurs   
9    00000c289a1829a808ac09c00daf10bc3c4e223b                 lunachicks   
10   00000c289a1829a808ac09c00daf10bc3c4e223b           walls of jericho   
11   00000c289a1829a808ac09c00daf10bc3c4e223b             letzte instanz   
12   00000c289a1829a808ac09c00daf10bc3c4e223b                  goldfrapp   
13   00000c289a1829a808ac09c00daf10bc3c4e223b                 horrorpops   
15   00000c289a1829a808ac09c00daf10bc3c4e223b              jack off jill   
16   00000c289a1829a808ac09c00daf10bc3c4e223b           babes in toyland   
17   00000c289a1829a808ac09c00daf10bc3c4e223b           dropkick murphys   
18   00000c289a1829a808ac09c00daf10bc3c4e223b              all:my:faults   
19   00000c289a1829a808ac09c00daf10bc3c4e223b                   le tigre   
20   00000c289a1829a808ac09c00daf10bc3c4e223b                 schandmaul   
21   00000c289a1829a808ac09c00daf10bc3c4e223b                      edguy   
22   00000c289a1829a808ac09c00daf10bc3c4e223b        maximum the hormone   
23   00000c289a1829a808ac09c00daf10bc3c4e223b                   all ends   
24   00000c289a1829a808ac09c00daf10bc3c4e223b               jack johnson   
25   00000c289a1829a808ac09c00daf10bc3c4e223b                  eluveitie   
26   00000c289a1829a808ac09c00daf10bc3c4e223b                  rasputina   
27   00000c289a1829a808ac09c00daf10bc3c4e223b      london after midnight   
28   00000c289a1829a808ac09c00daf10bc3c4e223b                the killers   
30   00000c289a1829a808ac09c00daf10bc3c4e223b               judas priest   
31   00000c289a1829a808ac09c00daf10bc3c4e223b                 rob zombie   
32   00000c289a1829a808ac09c00daf10bc3c4e223b               the bosshoss   
..                                        ...                        ...   
78   00001411dc427966b17297bf4d69e7e193135d89        heavy heavy low low   
79   00001411dc427966b17297bf4d69e7e193135d89               hot hot heat   
80   00001411dc427966b17297bf4d69e7e193135d89                  hadouken!   
81   00001411dc427966b17297bf4d69e7e193135d89                the wombats   
84   00001411dc427966b17297bf4d69e7e193135d89                      uffie   
85   00001411dc427966b17297bf4d69e7e193135d89    the last shadow puppets   
86   00001411dc427966b17297bf4d69e7e193135d89                 boys noize   
87   00001411dc427966b17297bf4d69e7e193135d89             built to spill   
88   00001411dc427966b17297bf4d69e7e193135d89                    nujabes   
89   00001411dc427966b17297bf4d69e7e193135d89          the rocket summer   
90   00001411dc427966b17297bf4d69e7e193135d89              little dragon   
92   00001411dc427966b17297bf4d69e7e193135d89             the album leaf   
93   00001411dc427966b17297bf4d69e7e193135d89            the microphones   
94   00001411dc427966b17297bf4d69e7e193135d89        simian mobile disco   
95   00001411dc427966b17297bf4d69e7e193135d89                     m.i.a.   
96   00001411dc427966b17297bf4d69e7e193135d89        death cab for cutie   
97   00001411dc427966b17297bf4d69e7e193135d89               patrick wolf   
98   00001411dc427966b17297bf4d69e7e193135d89         the fiery furnaces   
99   00001411dc427966b17297bf4d69e7e193135d89                 digitalism   
100  00004d2ac9316e22dc007ab2243d6fcb239e707d                 current 93   
101  00004d2ac9316e22dc007ab2243d6fcb239e707d                       coil   
103  00004d2

In [20]:
user_data_with_artist_plays.query('plays>40000')

users               artist-name  \
27358     006261139d787c1e43b4c69d304f2772367c1005                   garbage   
43276     00a20b9791abd8b29903a8a43e343ae93a98d9fd                 lil wayne   
166489    0268c4ff8eba994c93fc0e49644bac7b49caa068  mindless self indulgence   
175680    028b91859a012251da23c3dbfd2215154a789f9f                       afi   
191656    02ccf45baa7fe62f0935b8a6a64ff8869a7b0387        christina aguilera   
207045    030b70e6467476cd8b57933b04a07f0f45599d8c               hilary duff   
224393    034e097d2768be93762fd26f445bc096d613770a                      kiss   
427293    0649b561f5bcc119525300890c51762f86db069a              super junior   
494042    073689cd85d6f876b0b1123598c53194b2d21198                       boa   
556796    082279c9db5330c25a4e0ceae275a9fc79c753c4               céline dion   
634600    09490bb4034066761d59985dbe93e0119fcc1006                     oasis   
671310    09d12dfa05a0852053a9017121034a837fa4019e              alice cooper   
700681    0a3a8bc32230b79f72169cfdea72df97f122bf29                    sum 41   
763447    0b2956b319a3ac466b0cf1a8c49fa73498d0898c                 in flames   
767732    0b3a270a4225e019f37fec793e4029126620d253                 disturbed   
911812    0d598f7353a0fb7f9f859fd5a25caea6008028dd                 green day   
1010761   0ebecedb3cef2347ebab2936d30c1a488b8c43d0             chico buarque   
1010762   0ebecedb3cef2347ebab2936d30c1a488b8c43d0                  vanguart   
1010763   0ebecedb3cef2347ebab2936d30c1a488b8c43d0     engenheiros do hawaii   
1010764   0ebecedb3cef2347ebab2936d30c1a488b8c43d0     johann sebastian bach   
1010765   0ebecedb3cef2347ebab2936d30c1a488b8c43d0              los hermanos   
1010766   0ebecedb3cef2347ebab2936d30c1a488b8c43d0           mallu magalhães   
1078487   0fb28083be904ad6942facd7430edce1b1a1a080            arctic monkeys   
1151872   10cb0b311118f33782cf487bbc747404ac21d813                       서태지   
1194005   116a9d9932c958c31a9ac682eccdedd718a7221a                      坂本真綾   
1203885   1190d7fbc0bf25d2d05fa24ccd811446d6fbd3e8                   madonna   
1342696   138ee9c74a31ec7943029438c15b264194e0f8a8                 midge ure   
1381381   141f6a3c2b664f259dfe606b1937777360c0bd86  mindless self indulgence   
1423604   14c00864e18b9f825cba1bd8003e6816e50cc7e6                portishead   
1435217   14ea4c6f3c2e86b4937f1158bd13d3173d780bd7               dean martin   
...                                            ...                       ...   
15884170  e81d162d0c6dae638e443e7e25bb2df9256548a4                  slipknot   
15923164  e8a5cf1ebd6b6b9bffdb33d192961ec02f9b09e7     red hot chili peppers   
15935648  e8d62d77e339adf892b8e741ce33b6050c7d9d9c                     oasis   
16043104  ea5913789f8cba953d1a6b48e730856630db2005                 in flames   
16083622  eaf2ef0be4d0d7135cc81ef8db0b556f1df3f7ae           subway to sally   
16165011  ec1d53d586bcf7ab6756f1f02d5d78cfd38e484d                      muse   
16234733  ed209d795d57d32174a1e1a8cf329ba3aa528e3f                 daft punk   
16241634  ed3aaded13afcca8975afe7bfac9a582cb259a16         marian mcpartland   
16505338  f0f8c5437d8d6e770d63fbccf428610fccca0772           louis armstrong   
16508403  f103f240dad1218a17a1b539e50422c234f8aa49              mariah carey   
16582714  f21bd3764c6ee7968a8a5102f2076dc029b4525f                       fey   
16609893  f27c8d76cf15dd6e79fec7affb684804475292de                   a*teens   
16610132  f27db36f5b8836e487110f02c1b78ad8058a1d03                    brandy   
16634409  f2d3fdfe77849db1419a9cbdcbbc291888c3ddc4                      a-ha   
16637083  f2dc609020e6816705e75d9dcfd6e6d244824974            milla jovovich   
16640365  f2e7aef2bb4c6fcae55c6cf3a84e42de44bc0fcf               katie melua   
16809224  f55928c81b10964f51f4cf12ffdd8c6f5b27f356                    enigma   
16927429  f704d4f3479aa73108e2727db6207c003689356f                    younha   
16931710  f714eaff944bdf422df2a42354d31c40a0e

In [24]:
combined = user_data_popular_artists.merge(user_profiles, left_on = 'users', right_on = 'users', how = 'left')
usa_data = combined.query('country == \'United States\'')
usa_data.head()

users        artist-name  plays  \
156  00007a47085b9aab8af55f52ec8846ac479ac4fe   devendra banhart    456   
157  00007a47085b9aab8af55f52ec8846ac479ac4fe   boards of canada    407   
158  00007a47085b9aab8af55f52ec8846ac479ac4fe          cocorosie    386   
159  00007a47085b9aab8af55f52ec8846ac479ac4fe         aphex twin    213   
160  00007a47085b9aab8af55f52ec8846ac479ac4fe  animal collective    203   

     total_artist_plays        country  
156             2366807  United States  
157             6115545  United States  
158             2194862  United States  
159             4248296  United States  
160             3495537  United States

In [25]:
combined.query('plays>100000')

users  \
34568     00a20b9791abd8b29903a8a43e343ae93a98d9fd   
155324    02ccf45baa7fe62f0935b8a6a64ff8869a7b0387   
542544    09d12dfa05a0852053a9017121034a837fa4019e   
617078    0b2956b319a3ac466b0cf1a8c49fa73498d0898c   
1159053   14ea4c6f3c2e86b4937f1158bd13d3173d780bd7   
1298741   177653480857c3bb69b9a71b4f7166b7cd62129c   
1353498   1872585e74857e4888dfa63bd1186d210aae7681   
1821162   20d54d757ff07da456dfaa26e9077f5fa12fe71a   
1914297   228eb001a7ad5408dce7d40859e5935081518ff1   
2170271   274f8ab91b73503c3a18cb5c230affa56e0a677d   
2264157   28f4de1761a599cf2b689bc6610d3d40a62caadd   
2324291   2a088c171293674c39d0e02f495c6f91362357b0   
2507156   2d5669ab469c8399e07e8ae34918e6309d574aad   
2852693   33b19ba7b795dd6abd8cb4e0ec9d27456f4a4044   
3001148   366c0b8cf44374df47d874b16f8a81e12c157c1f   
3498971   3f40dad7b10658c66c1de6d560c92ae2a7ccacbb   
4166200   4b79df05a80b733e6422e52e5d1f25b50cd3aadb   
4330180   4e773f3f8e3f74fa23836ede43d8364dd8b4062d   
4638643   54027330bb09fe82d2b7e85749d4041eab3d5e4e   
5337679   609d4e3aa03afeefa282d873d3abe7c484e21225   
5443486   6279d62ad11b724950845a026b0d4a70aec5b5e0   
5677810   66b94d3bff0458037b7c85650331a10727833a58   
6151014   6f460e97cc8512f300004ec6c697c2216ec6c28f   
6938460   7d8b040d3226b187b8a1a95ac1527f395373b51f   
7357696   8519545b80b95da502233743fa9bd1ff941ab13f   
7729721   8bc02e7e4842b0a3c33a17149ea1ea5b37be6273   
7798019   8d0384537845e7f2b1b8b3e8a9f67eb8d9439794   
8111123   92aa9c188586c2e57dfa76326ee8b8bdd62dd426   
8783645   9ed77196358c5a9aeff4543e43e11d6bf6d02d34   
9590714   ada8a9ac4f6ea943e6ed858e8f194947181e03d7   
10197619  b88d16f3ebdad0bf701ecd46cf4725ea31911849   
10197620  b88d16f3ebdad0bf701ecd46cf4725ea31911849   
10326013  baee6143fb184f2014f05c737c28cd57d6d0486f   
10809771  c3a03caf33ae7818d8e7783c4575bc63a594181b   
10856851  c46c9683e1ac940b53b8ea52ac27ce160fade9a2   
10974450  c6888d7be46acf6deab52f7bc2bd5900a1b216ba   
11535253  d09386fb62a50ae6d4daad5a17fecbf07faad701   
11554368  d0e63bd9ecdde014b0a389fe8ffeecc305428ad2   
11614507  d1f816fb11d62d24dd9a3babe4bb2e49b5444bbc   
11825607  d5c1fe51720f69baae1281e09efbc9080d7c304f   
12214252  dcce20638cf6b541dfebd820df1146abe4bf1e86   
13391354  f21bd3764c6ee7968a8a5102f2076dc029b4525f   
13413034  f27c8d76cf15dd6e79fec7affb684804475292de   
13573418  f55928c81b10964f51f4cf12ffdd8c6f5b27f356   
13671953  f714eaff944bdf422df2a42354d31c40a0e73240   
13894169  fb30d581e1ddf82812e7bdfae7a7d965a6cf54bc   

                                    artist-name   plays  total_artist_plays  \
34568                                 lil wayne  107758             2432188   
155324                       christina aguilera  135392             2680164   
542544                             alice cooper  134993             1542185   
617078                                in flames  112989            11288367   
1159053                             dean martin  288375              655025   
1298741                                    rush  100846             2518951   
1353498                             tokio hotel  141661              952834   
1821162                          marilyn manson  111455             6417868   
1914297                              the rasmus  100080             1156417   
2170271                                      u2  116025             8111215   
2264157                               lil wayne  113961             2432188   
2324291                        enrique iglesias  232650             1069095   
2507156                                    동방신기  114386             1170927   
2852693                                t.a.t.u.  186028             1818384   
3001148                          britney spears  157737             7465258   
3498971                                 madonna  109232             7633843   
4166200                             dir en grey  270122             2814331   
4330180                           mary j. blige  192749              950017   
46386

In [27]:
initial_rows = usa_data.shape[0]
print('Initial dataframe shape {0}'.format(usa_data.shape))
usa_data = usa_data.drop_duplicates(['users', 'artist-name'])
current_rows = usa_data.shape[0]
print('New dataframe shape {0}'.format(usa_data.shape))
print('Removed {0} rows'.format(initial_rows - current_rows))

Initial dataframe shape (2788019, 5)
New dataframe shape (2788013, 5)
Removed 6 rows


# Reshape data into sparse matrix

In [28]:
wide_artist_data = usa_data.pivot(index = 'artist-name', columns = 'users', values = 'plays').fillna(0)
wide_artist_data_sparse = csr_matrix(wide_artist_data.values)

In [33]:
wide_artist_data.head()

users               00007a47085b9aab8af55f52ec8846ac479ac4fe  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               0001a57568309b287363e72dc682e9a170ba6dc2  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               00024b5b85c40f990c28644d53257819980bf6bb  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               0002dd2154072434d26e5409faa591bfb260a01e  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               00032c7933e0eb05f2258f1147ef81a90f2d4d6c  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               00041cbfdd019b5431f926133266cc4ba38219bb  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               000429493d9716b66b02180d208d09b5b89fbe64  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               000701c3c006b091990162635b36b008c504c6a7  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               000752c87a61bc4247f5219b4769c347c0062c8a  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                  

In [34]:
wide_artist_data.shape

(9127, 66913)

In [43]:
wide_artist_data_sparse[1].data

array([ 305.,   31.,   66.,  251.,   21.,   47.,   27.,   32.])

In [35]:
wide_artist_data_sparse

<9127x66913 sparse matrix of type '<type 'numpy.float64'>'
	with 2788013 stored elements in Compressed Sparse Row format>

In [36]:
wide_artist_data_sparse.data

array([ 113.,  109.,  127., ...,  126.,  428.,  391.])

# Apply KNN model

In [46]:
from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')


In [47]:
model_knn

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [48]:
model_knn.fit(wide_artist_data_sparse)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [25]:
model_knn

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [52]:
query_index = np.random.choice(wide_artist_data.shape[0])


In [53]:
query_index

8551

In [54]:
wide_artist_data.loc['the beatles']

users
00007a47085b9aab8af55f52ec8846ac479ac4fe      0.000
0001a57568309b287363e72dc682e9a170ba6dc2    167.000
00024b5b85c40f990c28644d53257819980bf6bb      0.000
0002dd2154072434d26e5409faa591bfb260a01e      0.000
00032c7933e0eb05f2258f1147ef81a90f2d4d6c     68.000
00041cbfdd019b5431f926133266cc4ba38219bb      0.000
000429493d9716b66b02180d208d09b5b89fbe64    807.000
000701c3c006b091990162635b36b008c504c6a7      0.000
000752c87a61bc4247f5219b4769c347c0062c8a    248.000
0008538a0f505f72fdd66af3c4c71aef8d3bdea4      0.000
0008b075deee53a3a090668c7ec581e15c3d8430    225.000
000912716c36131c4d8591da475c93337e7196a7      0.000
0009fbcb5120332beefdb12af5e60957688f6765      0.000
000c17602167c89588c25f40310d7c29e2275c22      0.000
000d109e4a25299eeef77a14d6b6a81479d1ac0e     82.000
000d878a6b2c852089e1a57698dc7f7df76cde6a    615.000
000d8c54934cc3a9eab276ccb412dbf52b980a44      0.000
000f5ca9514226b8b1589f57f02bbdc839bf8727      0.000
001169ca4be3a1ed81e2f510039f3dcd663313e8      0.000
0013a2

In [57]:
wide_artist_data.iloc[4000, :].reshape(1, -1)

/usr/local/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  if __name__ == '__main__':


array([[ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [67]:
query_index = 7618

distances, indices = model_knn.kneighbors(wide_artist_data.iloc[query_index, :].values.reshape(1, -1), n_neighbors = 6)
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(wide_artist_data.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, wide_artist_data.index[indices.flatten()[i]], distances.flatten()[i]))
        
        

Recommendations for the beatles:

1: john lennon, with distance of 0.550101069694:
2: george harrison, with distance of 0.603719089391:
3: the rolling stones, with distance of 0.643655903479:
4: ringo starr, with distance of 0.673692060751:
5: led zeppelin, with distance of 0.674702665716:


In [60]:
distances

array([[ 0.        ,  0.61484033,  0.6557904 ,  0.67671898,  0.68284198,
         0.7227864 ]])

In [61]:
indices

array([[2893, 2724, 3704, 2905, 4972,  643]])

Recommendations for flesh field:

1: exilia, with distance of 0.614840326151:
2: indica, with distance of 0.65579039818:
3: flowing tears, with distance of 0.676718984191:
4: mankind is obsolete, with distance of 0.682841983433:
5: ashbury heights, with distance of 0.722786401013:


In [27]:
query_index

6675

In [28]:
distances

array([[ 0.        ,  0.6817363 ,  0.73388034,  0.73926189,  0.7485667 ,
         0.76342262]])

In [29]:
indices

array([[6675, 4856, 8748, 2798, 2840, 4600]])

In [77]:
def print_recommendations(query_index):
    distances, indices = model_knn.kneighbors(wide_artist_data.iloc[query_index, :].values.reshape(1, -1), n_neighbors = 6)
    for i in range(0, len(distances.flatten())):
        if i == 0:
            print('Recommendations with binary play data for {0}:\n'.format(wide_artist_data.index[query_index]))
        else:
            print('{0}: {1}, with distance of {2}:'.format(i, wide_artist_data.index[indices.flatten()[i]], distances.flatten()[i]))

In [97]:
inlist = wide_artist_data.index
#artist_name = 'the beatles'
#artist_name = 'see-saw'
#artist_name = 'pink floyd'
artist_name = 'michael jackson'

query_index = [x for x in range(len(inlist)) if inlist[x]==artist_name]
query_index

[5238]

In [98]:
print_recommendations(query_index)

Recommendations with binary play data for Index([u'michael jackson'], dtype='object', name=u'artist-name'):

1: janet jackson, with distance of 0.779977763442:
2: madonna, with distance of 0.804170677115:
3: mariah carey, with distance of 0.805428679137:
4: prince, with distance of 0.806056120552:
5: stevie wonder, with distance of 0.810470034036:


In [63]:
inlist = wide_artist_data.index

In [64]:
inlist

Index([u'!!!', u'#####', u'(+44)', u'(hed) planet earth', u'*nsync', u'*shels',
       u'+/-', u'+44', u'-m-', u'-oz-',
       ...
       u'동방신기', u'비', u'빅뱅', u'서태지', u'성시경', u'소녀시대', u'신화', u'이수영', u'이정현',
       u'이효리'],
      dtype='object', name=u'artist-name', length=9127)

# make all plays count binary

In [82]:
wide_artist_data_zero_one = wide_artist_data.apply(np.sign)
wide_artist_data_zero_one_sparse = csr_matrix(wide_artist_data_zero_one.values)

In [83]:
wide_artist_data_zero_one.head()

users               00007a47085b9aab8af55f52ec8846ac479ac4fe  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               0001a57568309b287363e72dc682e9a170ba6dc2  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               00024b5b85c40f990c28644d53257819980bf6bb  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               0002dd2154072434d26e5409faa591bfb260a01e  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               00032c7933e0eb05f2258f1147ef81a90f2d4d6c  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               00041cbfdd019b5431f926133266cc4ba38219bb  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               000429493d9716b66b02180d208d09b5b89fbe64  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               000701c3c006b091990162635b36b008c504c6a7  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                                                 0.000   

users               000752c87a61bc4247f5219b4769c347c0062c8a  \
artist-name                                                    
!!!                                                    0.000   
#####                                                  0.000   
(+44)                                                  0.000   
(hed) planet earth                                     0.000   
*nsync                  

In [84]:
wide_artist_data_zero_one_sparse.data

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [85]:
wide_artist_data_zero_one_sparse[7].data

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

# New KNN Model based on 0-1 values

In [86]:
from sklearn.neighbors import NearestNeighbors
model_nn_binary = NearestNeighbors(metric='cosine', algorithm='brute')
model_nn_binary.fit(wide_artist_data_zero_one_sparse)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [87]:
query_index = 4000
distances, indices = model_nn_binary.kneighbors(wide_artist_data_zero_one.iloc[query_index, :].reshape(1, -1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations with binary play data for {0}:\n'.format(wide_artist_data_zero_one.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, wide_artist_data_zero_one.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations with binary play data for joe budden:

1: jadakiss, with distance of 0.673887880506:
2: fabolous, with distance of 0.707922468236:
3: royce da 5'9", with distance of 0.714347393557:
4: styles p, with distance of 0.719508633398:
5: saigon, with distance of 0.720737719368:


/usr/local/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  from ipykernel import kernelapp as app


In [88]:
def print_recommendations(query_index):
    distances, indices = model_nn_binary.kneighbors(wide_artist_data_zero_one.iloc[query_index, :].values.reshape(1, -1), n_neighbors = 6)
    for i in range(0, len(distances.flatten())):
        if i == 0:
            print('Recommendations with binary play data for {0}:\n'.format(wide_artist_data_zero_one.index[query_index]))
        else:
            print('{0}: {1}, with distance of {2}:'.format(i, wide_artist_data_zero_one.index[indices.flatten()[i]], distances.flatten()[i]))

In [105]:
inlist = wide_artist_data.index
#artist_name = 'the beatles'
artist_name = 'see-saw'
#artist_name = 'pink floyd'
#artist_name = 'kenny g'
#artist_name = 'michael jackson'


query_index = [x for x in range(len(inlist)) if inlist[x]==artist_name]
query_index

[6800]

In [106]:
print_recommendations(query_index)

Recommendations with binary play data for Index([u'see-saw'], dtype='object', name=u'artist-name'):

1: fictionjunction yuuka, with distance of 0.796602865528:
2: ali project, with distance of 0.799280155919:
3: mitsumune shinkichi, with distance of 0.858865033593:
4: kotoko, with distance of 0.869452031172:
5: chikayo fukuda, with distance of 0.877501010612:


In [107]:
def print_recommendations_old(query_index):
    distances, indices = model_knn.kneighbors(wide_artist_data.iloc[query_index, :].values.reshape(1, -1), n_neighbors = 6)
    for i in range(0, len(distances.flatten())):
        if i == 0:
            print('Recommendations with binary play data for {0}:\n'.format(wide_artist_data.index[query_index]))
        else:
            print('{0}: {1}, with distance of {2}:'.format(i, wide_artist_data.index[indices.flatten()[i]], distances.flatten()[i]))

In [108]:
print_recommendations_old(query_index)

Recommendations with binary play data for Index([u'see-saw'], dtype='object', name=u'artist-name'):

1: the delgados, with distance of 0.404210117045:
2: jumbo, with distance of 0.508068565366:
3: death from above 1979, with distance of 0.570454676995:
4: dj sharpnel, with distance of 0.591499045656:
5: redalice, with distance of 0.611290498952:
